# Generated by Django 3.2.7 on 2021-09-11 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_projects', models.IntegerField()),
                ('avg_projects_rate', models.FloatField()),
                ('total_projects_likes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Project name')),
                ('photo', models.ImageField(blank=True, default='img/default.jpg', null=True, upload_to='images', verbose_name='Project photo')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Project description')),
                ('likes_counter', models.IntegerField(blank=True, null=True, verbose_name='Project likes')),
                ('likes_ratio', models.FloatField(blank=True, null=True, verbose_name='Project likes ratio')),
                ('source_link', models.CharField(blank=True, max_length=200, null=True, verbose_name='Project source link')),
                ('authors', models.ManyToManyField(blank=True, to='projects.Developer', verbose_name='Projects authors')),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_text', models.TextField()),
                ('vote', models.CharField(choices=[('up', 'vote up'), ('down', 'vote down')], max_length=100)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(blank=True, to='projects.Tags', verbose_name='Project technologies'),
        ),
    ]
