# Generated by Django 3.2.7 on 2021-09-11 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20210911_1503'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='review_text',
            new_name='text',
        ),
    ]
