# Generated by Django 3.2.7 on 2021-09-13 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_rename_review_text_review_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='photo',
            field=models.ImageField(blank=True, default='images/default-thumbnail.jpg', null=True, upload_to='photos', verbose_name='Project photo'),
        ),
    ]
