# Generated by Django 3.2.7 on 2021-09-13 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_project_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='photo',
            field=models.ImageField(blank=True, default='photos/default-thumbnail.jpg', null=True, upload_to='photos', verbose_name='Project photo'),
        ),
    ]
