# Generated by Django 3.2.7 on 2021-09-13 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_project_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='photo',
            new_name='image',
        ),
    ]
