# Generated by Django 3.2.4 on 2021-09-21 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('projects', '0008_rename_photo_project_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Developer',
        ),
        migrations.AlterField(
            model_name='project',
            name='authors',
            field=models.ManyToManyField(blank=True, null=True, to='users.Profile', verbose_name='Projects authors'),
        ),
    ]
