# Generated by Django 3.2.4 on 2021-09-28 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('projects', '0009_auto_20210921_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='authors',
        ),
        migrations.AddField(
            model_name='project',
            name='author',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile', verbose_name='Projects authors'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photos', verbose_name='Project photo'),
        ),
    ]
